# -*- coding: utf-8 -*-
"""Proyecto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uy3aul7E5yqO_aIWFuQqJbK-2C4odzup
"""

import random
from collections import Counter
from IPython.display import clear_output

def pedir_intento():
  while True:
    Intento = input("\nIngresa un número de 3 dígitos (000-999): ")
    if len(Intento) == 3 and Intento.isdigit():
        return [int(digito) for digito in Intento]
    else:
        print("\nError, volver a intentar")
def mostrar_victoria(intentoPC, NumSC, jugadasPC, contador):
    if intentoPC == NumSC:
      extra = "".join(map(str, intentoPC))
      print(f"Tu número es: {extra}")
      print(f"Mi cantidad de intentos fue: {contador}")
    else:
      for final in range(len(jugadasPC)):
        contador += 1
        final += 1
        jugadaCANON = jugadasPC[final]
        print(f"Intento {contador}: La computadora prueba con {''.join(map(str, jugadaCANON))}")
        if jugadaCANON == NumSC:
          break
      extra = "".join(map(str, jugadaCANON))
      print(f"Tu número es: {extra}")
      print(f"Mi cantidad de intentos fue: {contador}")
def mostrar_resumen_usuario(historial, pcnm, contador):
  historia = " otro: ".join(map(str, historial))
  extra = "".join(map(str, pcnm))
  print(f"\nTodos los intentos fueron: {historia}")
  print(f"\nGanaste, la respuesta correcta era: {extra}")
  print(f"\nIntentaste un total de: {contador}")


Elección = int(input("Elige el modo de juego: \nLa computadora piensa los 3 elementos y el usuario adivina. (1) \nEl usuario piensa los 3 elementos y la computadora adivina. (2)\n"))

while Elección != 1 and Elección != 2:
  print("Error, elige")
  Elección = int(input("1 o 2\n"))

if Elección == 1:
  clear_output()
  pista = 0
  pcnm = [random.randint(0, 9) for _ in range(3)]
  mia = []
  mia = pedir_intento()
  contador = 1
  historial = []
  while mia != pcnm:
    contador += 1
    pista = 0
    copia_secreta = pcnm.copy()
    for numero_usuario in mia:
      if numero_usuario in copia_secreta:
        pista += 1
        copia_secreta.remove(numero_usuario)
    print(f"Hay {pista} números en la combinación.")
    dato = "".join(map(str, mia))
    historial.append(dato)
    print("\nIntento fallido. Sigue intentando.")
    mia = pedir_intento()
  mostrar_resumen_usuario(historial, pcnm, contador)

elif Elección == 2:
  clear_output()
  NumSC = pedir_intento()
  jugadasPC = []
  for i in range(1000):
    jugadasPC.append([int(d) for d in f"{i:03d}"])
  contador = 0
  while True:
    contador += 1
    intentoPC = jugadasPC[0]
    print(f"Intento {contador}: La computadora prueba con {''.join(map(str, intentoPC))}")
    copia_secreta = NumSC.copy()
    pista = 0
    for numeroPCERDO in intentoPC:
      if numeroPCERDO in copia_secreta:
        pista += 1
        copia_secreta.remove(numeroPCERDO)
    if Counter(intentoPC) == Counter(NumSC):
      break
    sospechosos = []
    for n in jugadasPC:
      pistafake = 0
      duplicado = n.copy()
      for d in intentoPC:
        if d in duplicado:
          pistafake += 1
          duplicado.remove(d)
      if pistafake == pista:
        sospechosos.append(n)
    jugadasPC = sospechosos

  mostrar_victoria(intentoPC, NumSC, jugadasPC, contador)